[package]
name = "redis-connector-sink"
group = "am"
version = "0.1.0"
apiVersion = "0.1.0"
fluvio = "0.10.0"
description = ""
license = "Apache-2.0"
visibility = "public"

[direction]
 dest = true 

[deployment]
binary = "redis-connector-sink"

[custom]
name = "redis"
required = ["url"]

[custom.properties.url]
title = "Redis Sink Connector"
description = "Connector to write into Redis"
type = "string"

[secret.REDIS_URL]
type = "env"